// Environment variables for client-side usage
window.ENV = {
    OPENAI_API_KEY: 'YOUR_OPENAI_API_KEY',
    AISHUB_USERNAME: 'YOUR_AISHUB_USERNAME',
    DATALASTIC_API_KEY: 'YOUR_DATALASTIC_API_KEY',
    SEARATES_API_KEY: 'YOUR_SEARATES_API_KEY'
};