[build]
  publish = "."
  command = "echo 'No build needed - static files'"

[[redirects]]
  from = "/"
  to = "/costing-app.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/costing-app.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"